version: "3"
services:
  hoard:
    image: quay.io/monax/hoard:1.1.3
    ports:
      - "53431"
  postgres:
    image: postgres:9-alpine
    ports:
    - "5432"
    environment:
      POSTGRES_USER: blackstone_development
      POSTGRES_PASSWORD: blackstone_development
      POSTGRES_DB: blackstone_development
  chain:
    # We could reference hyperledger/burrow:$version directly here but for the sake of only specifying our dependency version
    # once we do it in the project Dockerfile
    build: .
    ports:
    # GRPC port for most interaction
    - "10997"
    # HTTP status/information port
    - "26658"
    volumes:
    - ./test/chain:/chain
    working_dir: /chain
    command:
    - burrow
    - start
  vent:
    image: quay.io/monax/vent:develop
    restart: always
    command:
    - --db-adapter
    - postgres
    - --db-url
    - postgres://blackstone_development:blackstone_development@postgres:5432/blackstone_development?sslmode=disable
    - --db-schema
    - blackstone_development
    - --grpc-addr
    - chain:10997
    - --log-level
    - info
    - --spec-file
    - /config/Tables.spec
    - --abi-dir
    - /abi/
    volumes:
    - ./api/sqlsol:/config
    - ./contracts/src/bin:/abi
    depends_on:
    - postgres
    - chain
  api:
    build: .
    environment:
      CI_PROJECT_DIR: /app
      HOARD_IP: hoard:53431
      NODE_ENV: testing
      MONAX_ECOSYSTEM: MONAX_PLATFORM
    volumes:
    - .:/app
    ports:
    - "3080:3080"
    - "9222:9222"
    working_dir: /app
    depends_on:
    - postgres
    - hoard
    - vent
    - chain
    command: "test/test_api.sh --runAPI"
