version: "3.4"
services:
  hoard:
    image: quay.io/monax/hoard:2.0.0
    ports:
      - "53431"
    environment:
      HOARD_JSON_CONFIG: '{"ListenAddress":"tcp://:53431","Storage":{"StorageType":"filesystem","AddressEncoding":"base32","RootDirectory":"/store"},"Logging":{"LoggingType":"logfmt","Channels":["info","trace"]}}'
  postgres:
    image: postgres:9-alpine
    ports:
    - "5432"
    environment:
      POSTGRES_USER: blackstone_development
      POSTGRES_PASSWORD: blackstone_development
      POSTGRES_DB: blackstone_development
  chain:
    # We could reference hyperledger/burrow:$version directly here but for the sake of only specifying our dependency version
    # once we do it in the project Dockerfile
    build: .
    ports:
    # GRPC port for most interaction
    - "10997"
    # HTTP status/information port
    - "26658"
    volumes:
    - ./test/chain:/chain
    working_dir: /chain
    command:
    - /bin/sh
    - -c
    - burrow start &> burrow.log
  vent:
    image: quay.io/monax/burrow:0.24.0-dev-2019-02-26-8b59aade
    restart: always
    command:
    - vent
    - start
    - --db-adapter
    - postgres
    - --db-url
    - postgres://blackstone_development:blackstone_development@postgres:5432/blackstone_development?sslmode=disable
    - --db-schema
    - data
    - --grpc-addr
    - chain:10997
    - --log-level
    - info
    - --spec
    - /app/api/sqlsol
    - --abi
    - /app/contracts/src/bin
    volumes:
    - .:/app
    depends_on:
    - postgres
    - chain
  api:
    build: .
    environment:
      CI_PROJECT_DIR: /app
      API_DIRECTORY: /app/api
      NODE_ENV: dev
      HOARD_IP: hoard:53431
      IDENTITY_PROVIDER: MONAX_PLATFORM
      CONTRACTS_DEPLOYMENT_ADDRESS: F390C8CA854874472CAD38C0135F78097BCB632D
      CHAIN_URL_GRPC: chain:10997
      POSTGRES_DB_DATABASE: blackstone_development
      POSTGRES_DB_USER: blackstone_development
      POSTGRES_DB_PASSWORD: blackstone_development
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_SCHEMA: customers
      POSTGRES_DB_SCHEMA_VENT: data
      HOARD_SALT: hoard-salt
      PUBLIC_ID: hoard-api-test-1
    volumes:
    - .:/app
    ports:
    - "3080:3080"
    - "9222:9222"
    working_dir: /app
    depends_on:
    - postgres
    - hoard
    - vent
    - chain
    command: "test/test_api.sh --runAPI"
